### ISSUE TITLE
history为browser的情况下，build后部署dist文件夹会出现css、js404的情况

### ISSUE THREAD

**Issue by wongzzh** [hqwlkj/umi-dva-antd-mobile#12]
出现的404的文件名为：vendors.dde52742.chunk.css，vendors.8cce56e1.async.js，p__Form__index.39b0fd98.chunk.css，p__Form__index.dc85fe19.async.js

然而同样的代码只把history改为hash模式，build后部署就是正常的。

**Comment by hqwlkj** [comment]
![image](https://user-images.githubusercontent.com/12181423/58389773-d11b8180-805f-11e9-9079-8f61d27f76b3.png)

你是更新的最新代码吗？

**Comment by jackqth** [comment]
同样的问题，打包后的路径会按照page里的路径，导致打包后项目找不到css和js文件

**Comment by hqwlkj** [comment]
@jackqth  能提供一下你的环境版本和 重现方式吗？

**Comment by jackqth** [comment]
![image](https://user-images.githubusercontent.com/16730906/59403252-837b7480-8dd4-11e9-8940-ab670ef6dd84.png)
已经解决了，改成browser模式后 把这两个值设置成“/” 就没有问题了

**Comment by jackqth** [comment]
![image](https://user-images.githubusercontent.com/16730906/59409412-c34c5700-8de8-11e9-9282-6a8b41a7cf31.png)
已经得到解决，当我把这两个值设置为“/”之后打包就没有了问题，不会出现文件路径问题
