### ISSUE TITLE
我想要参考 你的抽奖模块是怎么弄的。

### ISSUE THREAD

**Issue by JanesChan** [hqwlkj/umi-dva-antd-mobile#15]
最近公司需要做一个h5的抽奖页面，看着你的抽奖页面效果不错，想知道你是如何实现的。

**Comment by hqwlkj** [comment]
@XiaoHuiHui-ad  源码参考地址 链接:https://pan.baidu.com/s/13ZJRZC_tQyk597eyOYQiSA  密码:dfn8

**Comment by XiaoHuiHui-ad** [comment]
> @XiaoHuiHui-ad 源码参考地址 链接:https://pan.baidu.com/s/13ZJRZC_tQyk597eyOYQiSA 密码:dfn8
> 
> 希望能够帮助你。

感谢 分享

**Comment by suncunhu** [comment]
已过期 😢

**Comment by hqwlkj** [comment]
@suncunhu  链接: https://pan.baidu.com/s/1zCace8rvBMcx9jGUMu8tWQ 提取码: k974 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by suncunhu** [comment]
@hqwlkj  好的 👌
