### ISSUE TITLE
关于项目中使用的parsec-ls包问题

### ISSUE THREAD

**Issue by JanesChan** [hqwlkj/umi-dva-antd-mobile#16]
我看到项目中有用到这个parsec-ls包，请问这个是什么包 有什么用。有文档可以看吗？

**Comment by hqwlkj** [comment]
@JanesChan  你可以不使用这个包，直接使用`localStorage`，`parsec-ls`包是 一个对 `localStorage` 进行了封装处理，[parsec-ls](https://www.npmjs.com/package/parsec-ls) api
