### ISSUE TITLE
抽奖大转盘 DEMO 源码地址

### ISSUE THREAD

**Issue by hqwlkj** [hqwlkj/umi-dva-antd-mobile#17]
链接:https://pan.baidu.com/s/1ZuHpqRYjOOzD4ZZJzeSayg  密码:1lcv

**Comment by Hxiaongrong** [comment]
这个转盘不是demo里的转盘啊

**Comment by hqwlkj** [comment]
> 啊

你有什么需求，转盘代码本来就是提供给大家进行参考的，如果有不同的地方自己可以手动修改，谢谢你的关注。
