### ISSUE TITLE
config.js中部分配置项需要删除，否则打包之后运行报错

### ISSUE THREAD

**Issue by zhangshuai0101** [hqwlkj/umi-dva-antd-mobile#21]

**Comment by hqwlkj** [comment]
能具体点吗？ @zhangshuai0101

**Comment by zhangshuai0101** [comment]
> 能具体点吗？ @zhangshuai0101

我删减了一下 贴出来你看下
![image](https://user-images.githubusercontent.com/40013310/60086138-23d67f00-976d-11e9-92d2-bb61c9967a0c.png)
![image](https://user-images.githubusercontent.com/40013310/60086155-2afd8d00-976d-11e9-8b06-024685db255c.png)
