### ISSUE TITLE
git clone之后run没问题，但build会报错

### ISSUE THREAD

**Issue by gugegev5** [hqwlkj/umi-dva-antd-mobile#22]
ERROR  Failed to compile with 1 errors

 error

umi.0432bf59.js from UglifyJs
Unexpected token: keyword «const» [umi.0432bf59.js:38316,6]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! umi-dva-antd-mobile@1.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the umi-dva-antd-mobile@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hqwlkj** [comment]
@gugegev5  
``

**Comment by gugegev5** [comment]
build成功了，感谢！
