### ISSUE TITLE
您好，路由如何设置？

### ISSUE THREAD

**Issue by jason19901028** [hqwlkj/umi-dva-antd-mobile#23]
在router.config.js文件中增加了一条
  { path: '/echarts', component: './echarts/index', title: '报表'},
结果就直接跳转到403页面了，地址栏是跳转了，但是内容到了403页面，不知道该怎么设置？
![image](https://user-images.githubusercontent.com/25576700/60770781-54290080-a111-11e9-9a42-25a91455eeb1.png)

**Comment by hqwlkj** [comment]
看你的配置是没有问题，你的 `echarts ` 文件是否存在呢？
