### ISSUE TITLE
如何在项目中关闭微信开发？

### ISSUE THREAD

**Issue by 13007640364** [hqwlkj/umi-dva-antd-mobile#24]
我需要怎样配置才能让程序跑在微信的时候，不用去执行'src/utils/wx.tsx'文件

**Comment by 13007640364** [comment]
注释掉这段代码后，我解决了这个问题
![image](https://user-images.githubusercontent.com/35397893/61426414-e8cf0200-a94c-11e9-9efc-e4b30c0c3283.png)

**Comment by hqwlkj** [comment]
@13007640364 是的，例子中有的。
