### ISSUE TITLE
支持微信开发有哪些特性啊？

### ISSUE THREAD

**Issue by theprimone** [hqwlkj/umi-dva-antd-mobile#26]
除了 #24 中的判断了微信环境外还有什么特性吗？

**Comment by theprimone** [comment]
吐槽一下，明明启用了代码检查，结果我提交代码一堆格式报错。看了又得自己造轮子了\ _(:3J∠)\_

**Comment by hqwlkj** [comment]
感谢吐槽，由于近期工作安排较紧，没有及时更新，十分抱歉。同时也欢迎大家参与共建

**Comment by theprimone** [comment]
本来我就以为在此基础上维护的，但是代码检查都过不了... ...遂，自己折腾了😂
