### ISSUE TITLE
关于wx分支的疑问

### ISSUE THREAD

**Issue by szy0syz** [hqwlkj/umi-dva-antd-mobile#28]
你好楼主，冒昧的问下，wx分支比master分支少了22个commits，应该是说wx分支少了些功能和bug修复吗？

**Comment by hqwlkj** [comment]
不是的 master 分支下新增了一些 demo 代码，所以提交 的代码不影响框架和 bug 修复。具体的可以查询提交记录。

**Comment by szy0syz** [comment]
好的👌。 Jerry 邮箱：szy0syz@gmail.com 签名由 网易邮箱大师 定制 在2019年08月24日 15:15，Yanghc 写道： 不是的 master 分支下新增了一些 demo 代码，所以提交 的代码不影响框架和 bug 修复。具体的可以查询提交记录。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
