### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by caoshining** [hqwlkj/umi-dva-antd-mobile#29]
现在的像素单位都是写死的吗 不需要进行适配吗老铁

**Comment by hqwlkj** [comment]
框架已经处理了适配的问题，你就按照设计稿的 750 px   进行开发就好了

**Comment by HSQCoollaughing** [comment]
框架已经处理了适配的问题，你就按照设计稿的 750 px 进行开发就好了  是用postcss-pxtorem插件吗？
大佬
