### ISSUE TITLE
问一下支持VW高清方案吗大神～

### ISSUE THREAD

**Issue by BenlovedLamphere** [hqwlkj/umi-dva-antd-mobile#3]
问一下支持VW高清方案吗大神～

**Comment by hqwlkj** [comment]
@BenlovedLamphere  支持的，在例子中就是 使用的 `vw`

**Comment by BenlovedLamphere** [comment]
@hqwlkj 多谢大神～

**Comment by hqwlkj** [comment]
@BenlovedLamphere  客气了，再说了我也不是什么大神，就是站在大神肩上的一位普通的码农:joy::joy::joy:

**Comment by BenlovedLamphere** [comment]
@hqwlkj 跑起来了，蔚来那个背景音乐不错啊。啥歌～

**Comment by hqwlkj** [comment]
@BenlovedLamphere  客户提供的 :grin: :grin: :grin:

**Comment by BenlovedLamphere** [comment]
@hqwlkj 打扰您一下，我跑完你的例子没啥问题，但是我想学着你的例子自己搭一下，就有问题了。

我想启用postcss-px-to-viewport这个插件，但安装后找不到在哪里进行设置，我在.umirc.js中设置如下：

`export default {
  treeShaking: true,
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: { webpackChunkName: true },
      title: 'TestMobile',
      dll: true,
      routes: {
        exclude: [
        
          /models\//,
          /services\//,
          /model\.(t|j)sx?$/,
          /service\.(t|j)sx?$/,
        
          /components\//,
        ],
      },
      // hd:true,
      extraPostCSSPlugins:[
        'postcss-px-to-viewport',{
          unitToConvert: 'px',
          viewportWidth: 750,
          unitPrecision: 5,
          propList: ['*'],
          viewportUnit: 'vw',
          fontViewportUnit: 'vw',
          selectorBlackList: [],
          minPixelValue: 1,
          mediaQuery: false,
          replace: true,
          exclude: [],
          landscape: false,
          landscapeUnit: 'vw',
          // landscapeWidth: 568
        }
      ]
    }],
  ],
}
`

但extraPostCSSPlugins的部分根本没生效，想请教大神考虑什么样的原因呢？

**Comment by DXDZY** [comment]
大神请教个问题啊，我看您使用了vw方案，为啥生成页面里的样式还是px的单位那？
