### ISSUE TITLE
项目运行起来如下图,除了首页,样式完全错乱

### ISSUE THREAD

**Issue by darkfiredarkhalo** [hqwlkj/umi-dva-antd-mobile#34]
![WechatIMG20](https://user-images.githubusercontent.com/13959162/72246044-dd733f80-362c-11ea-8c31-325dbdebce69.jpeg)
安卓和iOS一样,微信浏览器内也是

**Comment by hqwlkj** [comment]
目前项目在升级，导致了`ant-design-mobile `的样式加载出现了问题，目前在处理中。

**Comment by xclw2000** [comment]
> 目前项目在升级，导致了`ant-design-mobile `的样式加载出现了问题，目前在处理中。

大概什么时候能好呢？

**Comment by is7and11** [comment]
已经start项目了.请问有预计升级完成的时间吗？谢谢

**Comment by hqwlkj** [comment]
@is7and11  感谢，近期项目安排时间比较紧，我会抽出时间来升级的。

**Comment by coocier** [comment]
@xclw2000  该版本 0d3a7d5ed676c91a2961d19b6054f2e1bdf34beb 只需要删除 config.ts 文件中的  
```
 cssLoaderOptions: {
    modules: true,
  },
```
即可显示正常

**Comment by coocier** [comment]
@xclw2000  该版本 0d3a7d5ed676c91a2961d19b6054f2e1bdf34beb 下代码只需要删除 config.ts 文件中的  
```
 cssLoaderOptions: {
    modules: true,
  },
```
即可显示正常
