### ISSUE TITLE
使用浏览器调试手机端，页面过长不显示滚动条，也无法下拉

### ISSUE THREAD

**Issue by comeonlll** [hqwlkj/umi-dva-antd-mobile#41]
使用浏览器调试手机端，页面过长不显示滚动条，也无法下拉

![image](https://user-images.githubusercontent.com/38073829/82655211-68f08300-9c54-11ea-8543-779cbee9ef18.png)

**Comment by hqwlkj** [comment]
你看看是不是 设置了 `overflow: hidden `

**Comment by comeonlll** [comment]
![image](https://user-images.githubusercontent.com/38073829/82771131-8a788700-9e6d-11ea-9438-707e69865666.png)
是的全局样式中设置了这个，现在已解决非常感谢
