### ISSUE TITLE
集成antv/f2图表使用时在不同浏览器的手机模式样式会改变且差异较大

### ISSUE THREAD

**Issue by comeonlll** [hqwlkj/umi-dva-antd-mobile#42]
谷歌浏览器效果：
![image](https://user-images.githubusercontent.com/38073829/84784843-58e27e00-b01d-11ea-99a0-74214668c754.png)
火狐浏览器效果：
![image](https://user-images.githubusercontent.com/38073829/84784984-83ccd200-b01d-11ea-9d89-dcdfe7d52340.png)

**Comment by hqwlkj** [comment]
这个需要你自己定义图表的高度来控制。
