### ISSUE TITLE
如何部署？

### ISSUE THREAD

**Issue by ThorLei** [hqwlkj/umi-dva-antd-mobile#5]

**Comment by ThorLei** [comment]
打包出来没有index.html。

**Comment by hqwlkj** [comment]
请参考：https://umijs.org/zh/guide/deploy.html#%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E5%9C%A8%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95%E6%88%96-cdn
